[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
fxhash = "0.2.1"
regex = "1.11.1"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
